### ISSUE TITLE
bug - compare_shap_and_KG

### ISSUE THREAD

**Issue by Sivler9** [JulesSanchez/X-NeSyL#1] opened 2021-12-10 10:18 UTC
Values written to https://github.com/JulesSanchez/X-NeSyL/blob/da333ceb84f00c821493a7c2f2828ff9dd337db4/utils/knowledge_graph.py#L13 are overwritten in https://github.com/JulesSanchez/X-NeSyL/blob/da333ceb84f00c821493a7c2f2828ff9dd337db4/utils/knowledge_graph.py#L23

Meaning that MonuMAI dataset can't be used without modifying the previous code and https://github.com/JulesSanchez/X-NeSyL/blob/da333ceb84f00c821493a7c2f2828ff9dd337db4/utils/knowledge_graph.py#L34-L38

The should have either unique identifiers or change https://github.com/JulesSanchez/X-NeSyL/blob/da333ceb84f00c821493a7c2f2828ff9dd337db4/utils/knowledge_graph.py#L38 to ```contrib = np.zeros((len(true_labels), knowledge_graph.shape[0]))```

**Comment by JulesSanchez** [comment] 2021-12-10 10:35
Hi, indeed you're right. It is caused by the iterative process of writing the code (I didn't have to work on both dataset at the same time). Thanks for pointing it out. I'll fix this when updating the code.

**Comment by JulesSanchez** [comment] 2021-12-22 13:48
Should be fixed

**Closed as completed by JulesSanchez** 2021-12-22 13:48 UTC
